apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgtoolbox
  namespace: system
  labels:
    app.kubernetes.io/name: pgtoolbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pgtoolbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pgtoolbox
    spec:
      serviceAccountName: pgtoolbox
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: manager
        image: controller:latest
        args:
        - --leader-elect
        - --metrics-bind-address=:8080
        - --health-probe-bind-address=:8081
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: probes
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
