---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - barmancloud.cnpg.io
  resources:
  - objectstores
  verbs:
  - get
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgtoolbox.fyannk.dev
  resources:
  - pgconsoles
  - pgtoolboxaccessrequests
  - pgtoolboxroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgtoolbox.fyannk.dev
  resources:
  - pgconsoles/finalizers
  - pgtoolboxroles/finalizers
  verbs:
  - update
- apiGroups:
  - pgtoolbox.fyannk.dev
  resources:
  - pgconsoles/status
  - pgtoolboxaccessrequests/status
  - pgtoolboxroles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pgtoolbox.fyannk.dev
  resources:
  - pgtoolboxusers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgtoolbox.fyannk.dev
  resources:
  - pgtoolboxusers/status
  verbs:
  - patch
  - update
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - backups
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - clusters/status
  verbs:
  - patch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - databaseroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - scheduledbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
