apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pgtoolbox.fullname" . }}
  namespace: {{ include "pgtoolbox.namespace" . }}
  labels:
    {{- include "pgtoolbox.labels" . | nindent 4 }}
