//go:build !ignore_autogenerated

/*
Copyright © contributors to the pgtoolbox project.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapAdminSpec) DeepCopyInto(out *BootstrapAdminSpec) {
	*out = *in
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapAdminSpec.
func (in *BootstrapAdminSpec) DeepCopy() *BootstrapAdminSpec {
	if in == nil {
		return nil
	}
	out := new(BootstrapAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleHistorySpec) DeepCopyInto(out *ConsoleHistorySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxRevisions != nil {
		in, out := &in.MaxRevisions, &out.MaxRevisions
		*out = new(int32)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		*out = new(int32)
		**out = **in
	}
	if in.PerObjectRevisions != nil {
		in, out := &in.PerObjectRevisions, &out.PerObjectRevisions
		*out = new(int32)
		**out = **in
	}
	if in.CoalesceWindow != nil {
		in, out := &in.CoalesceWindow, &out.CoalesceWindow
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleHistorySpec.
func (in *ConsoleHistorySpec) DeepCopy() *ConsoleHistorySpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleLogTailSpec) DeepCopyInto(out *ConsoleLogTailSpec) {
	*out = *in
	if in.Lines != nil {
		in, out := &in.Lines, &out.Lines
		*out = new(int32)
		**out = **in
	}
	if in.MaxBytes != nil {
		in, out := &in.MaxBytes, &out.MaxBytes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleLogTailSpec.
func (in *ConsoleLogTailSpec) DeepCopy() *ConsoleLogTailSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleLogTailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleMetricsSpec) DeepCopyInto(out *ConsoleMetricsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleMetricsSpec.
func (in *ConsoleMetricsSpec) DeepCopy() *ConsoleMetricsSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleMetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleSpec) DeepCopyInto(out *ConsoleSpec) {
	*out = *in
	if in.AllowOperations != nil {
		in, out := &in.AllowOperations, &out.AllowOperations
		*out = new(bool)
		**out = **in
	}
	if in.AllowLogs != nil {
		in, out := &in.AllowLogs, &out.AllowLogs
		*out = new(bool)
		**out = **in
	}
	if in.AllowAccessReview != nil {
		in, out := &in.AllowAccessReview, &out.AllowAccessReview
		*out = new(bool)
		**out = **in
	}
	if in.AllowClusterCatalogs != nil {
		in, out := &in.AllowClusterCatalogs, &out.AllowClusterCatalogs
		*out = new(bool)
		**out = **in
	}
	if in.AllowInsecureLinks != nil {
		in, out := &in.AllowInsecureLinks, &out.AllowInsecureLinks
		*out = new(bool)
		**out = **in
	}
	if in.APIRequestTimeout != nil {
		in, out := &in.APIRequestTimeout, &out.APIRequestTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.EventsMaxAge != nil {
		in, out := &in.EventsMaxAge, &out.EventsMaxAge
		*out = new(metav1.Duration)
		**out = **in
	}
	in.LogTail.DeepCopyInto(&out.LogTail)
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.History.DeepCopyInto(&out.History)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleSpec.
func (in *ConsoleSpec) DeepCopy() *ConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(ConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceSpec) DeepCopyInto(out *EvidenceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceSpec.
func (in *EvidenceSpec) DeepCopy() *EvidenceSpec {
	if in == nil {
		return nil
	}
	out := new(EvidenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceStatus) DeepCopyInto(out *EvidenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceStatus.
func (in *EvidenceStatus) DeepCopy() *EvidenceStatus {
	if in == nil {
		return nil
	}
	out := new(EvidenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureSpec) DeepCopyInto(out *ExposureSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(ExposureTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayExposureSpec)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureSpec.
func (in *ExposureSpec) DeepCopy() *ExposureSpec {
	if in == nil {
		return nil
	}
	out := new(ExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureTLSSpec) DeepCopyInto(out *ExposureTLSSpec) {
	*out = *in
	if in.CertificateSecretRef != nil {
		in, out := &in.CertificateSecretRef, &out.CertificateSecretRef
		*out = new(LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureTLSSpec.
func (in *ExposureTLSSpec) DeepCopy() *ExposureTLSSpec {
	if in == nil {
		return nil
	}
	out := new(ExposureTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayExposureSpec) DeepCopyInto(out *GatewayExposureSpec) {
	*out = *in
	out.ParentRef = in.ParentRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayExposureSpec.
func (in *GatewayExposureSpec) DeepCopy() *GatewayExposureSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayExposureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayParentRef) DeepCopyInto(out *GatewayParentRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayParentRef.
func (in *GatewayParentRef) DeepCopy() *GatewayParentRef {
	if in == nil {
		return nil
	}
	out := new(GatewayParentRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
	if in.PullSecrets != nil {
		in, out := &in.PullSecrets, &out.PullSecrets
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExtraEgress != nil {
		in, out := &in.ExtraEgress, &out.ExtraEgress
		*out = make([]v1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgAdminSpec) DeepCopyInto(out *PgAdminSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgAdminSpec.
func (in *PgAdminSpec) DeepCopy() *PgAdminSpec {
	if in == nil {
		return nil
	}
	out := new(PgAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgAdminStorageSpec) DeepCopyInto(out *PgAdminStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgAdminStorageSpec.
func (in *PgAdminStorageSpec) DeepCopy() *PgAdminStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PgAdminStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgConsole) DeepCopyInto(out *PgConsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgConsole.
func (in *PgConsole) DeepCopy() *PgConsole {
	if in == nil {
		return nil
	}
	out := new(PgConsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgConsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgConsoleList) DeepCopyInto(out *PgConsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgConsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgConsoleList.
func (in *PgConsoleList) DeepCopy() *PgConsoleList {
	if in == nil {
		return nil
	}
	out := new(PgConsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgConsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgConsoleSpec) DeepCopyInto(out *PgConsoleSpec) {
	*out = *in
	out.CNPGClusterRef = in.CNPGClusterRef
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Proxy.DeepCopyInto(&out.Proxy)
	in.PgAdmin.DeepCopyInto(&out.PgAdmin)
	in.Console.DeepCopyInto(&out.Console)
	in.Evidence.DeepCopyInto(&out.Evidence)
	in.Exposure.DeepCopyInto(&out.Exposure)
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
	in.PodSecurityContext.DeepCopyInto(&out.PodSecurityContext)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgConsoleSpec.
func (in *PgConsoleSpec) DeepCopy() *PgConsoleSpec {
	if in == nil {
		return nil
	}
	out := new(PgConsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgConsoleStatus) DeepCopyInto(out *PgConsoleStatus) {
	*out = *in
	out.UserSync = in.UserSync
	out.Evidence = in.Evidence
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgConsoleStatus.
func (in *PgConsoleStatus) DeepCopy() *PgConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(PgConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxAccessRequest) DeepCopyInto(out *PgToolBoxAccessRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxAccessRequest.
func (in *PgToolBoxAccessRequest) DeepCopy() *PgToolBoxAccessRequest {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxAccessRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgToolBoxAccessRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxAccessRequestList) DeepCopyInto(out *PgToolBoxAccessRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgToolBoxAccessRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxAccessRequestList.
func (in *PgToolBoxAccessRequestList) DeepCopy() *PgToolBoxAccessRequestList {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxAccessRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgToolBoxAccessRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxAccessRequestSpec) DeepCopyInto(out *PgToolBoxAccessRequestSpec) {
	*out = *in
	out.PgConsoleRef = in.PgConsoleRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxAccessRequestSpec.
func (in *PgToolBoxAccessRequestSpec) DeepCopy() *PgToolBoxAccessRequestSpec {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxAccessRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxAccessRequestStatus) DeepCopyInto(out *PgToolBoxAccessRequestStatus) {
	*out = *in
	if in.DecidedAt != nil {
		in, out := &in.DecidedAt, &out.DecidedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxAccessRequestStatus.
func (in *PgToolBoxAccessRequestStatus) DeepCopy() *PgToolBoxAccessRequestStatus {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxAccessRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxUser) DeepCopyInto(out *PgToolBoxUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxUser.
func (in *PgToolBoxUser) DeepCopy() *PgToolBoxUser {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgToolBoxUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxUserList) DeepCopyInto(out *PgToolBoxUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PgToolBoxUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxUserList.
func (in *PgToolBoxUserList) DeepCopy() *PgToolBoxUserList {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PgToolBoxUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxUserSpec) DeepCopyInto(out *PgToolBoxUserSpec) {
	*out = *in
	out.PgConsoleRef = in.PgConsoleRef
	if in.LocalPasswordSecretRef != nil {
		in, out := &in.LocalPasswordSecretRef, &out.LocalPasswordSecretRef
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxUserSpec.
func (in *PgToolBoxUserSpec) DeepCopy() *PgToolBoxUserSpec {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgToolBoxUserStatus) DeepCopyInto(out *PgToolBoxUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgToolBoxUserStatus.
func (in *PgToolBoxUserStatus) DeepCopy() *PgToolBoxUserStatus {
	if in == nil {
		return nil
	}
	out := new(PgToolBoxUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSecurityContextSpec) DeepCopyInto(out *PodSecurityContextSpec) {
	*out = *in
	if in.FSGroup != nil {
		in, out := &in.FSGroup, &out.FSGroup
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSecurityContextSpec.
func (in *PodSecurityContextSpec) DeepCopy() *PodSecurityContextSpec {
	if in == nil {
		return nil
	}
	out := new(PodSecurityContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyAuthenticationSpec) DeepCopyInto(out *ProxyAuthenticationSpec) {
	*out = *in
	in.BootstrapAdmin.DeepCopyInto(&out.BootstrapAdmin)
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(ProxyLocalSpec)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(ProxyOIDCSpec)
		**out = **in
	}
	if in.OpenShift != nil {
		in, out := &in.OpenShift, &out.OpenShift
		*out = new(ProxyOpenShiftSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyAuthenticationSpec.
func (in *ProxyAuthenticationSpec) DeepCopy() *ProxyAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyLocalSpec) DeepCopyInto(out *ProxyLocalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyLocalSpec.
func (in *ProxyLocalSpec) DeepCopy() *ProxyLocalSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyLocalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyOIDCSpec) DeepCopyInto(out *ProxyOIDCSpec) {
	*out = *in
	out.ClientSecretRef = in.ClientSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyOIDCSpec.
func (in *ProxyOIDCSpec) DeepCopy() *ProxyOIDCSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyOIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyOpenShiftSpec) DeepCopyInto(out *ProxyOpenShiftSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyOpenShiftSpec.
func (in *ProxyOpenShiftSpec) DeepCopy() *ProxyOpenShiftSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyOpenShiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxySpec) DeepCopyInto(out *ProxySpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Authentication.DeepCopyInto(&out.Authentication)
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxySpec.
func (in *ProxySpec) DeepCopy() *ProxySpec {
	if in == nil {
		return nil
	}
	out := new(ProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSyncStatus) DeepCopyInto(out *UserSyncStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSyncStatus.
func (in *UserSyncStatus) DeepCopy() *UserSyncStatus {
	if in == nil {
		return nil
	}
	out := new(UserSyncStatus)
	in.DeepCopyInto(out)
	return out
}
