apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/pgtoolbox.fyannk.dev_pgconsoles.yaml
- bases/pgtoolbox.fyannk.dev_pgtoolboxroles.yaml
- bases/pgtoolbox.fyannk.dev_pgtoolboxusers.yaml
- bases/pgtoolbox.fyannk.dev_pgtoolboxaccessrequests.yaml
