import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The key 'docs' is the sidebarId referenced in the navbar.
export default {
  docs: [{type: 'autogenerated', dirName: '.'}],
} satisfies SidebarsConfig;
